import { ArrowRight, ArrowUpRight, Check, FileText, Image, MousePointer2, PenLine, Type, StickyNote } from 'lucide-react'
import { Link } from 'react-router-dom'
import { Brand } from '../components/ui/Brand'
import { ThemeToggle } from '../components/ui/ThemeToggle'
import { ToolCatalog } from '../components/tools/ToolCatalog'
import { motion, useReducedMotion } from 'framer-motion'


export function LandingPage() {
  const reducedMotion = useReducedMotion()
  return <div className="landing">
    <header className="landing-header"><Link to="/" aria-label="Papertrail home"><Brand /></Link><nav aria-label="Main navigation"><a href="#editor">The editor</a><a href="#tools">PDF tools</a><a href="#pricing">Pricing</a></nav><div className="landing-header-actions"><ThemeToggle /><Link to="/login" className="text-link">Sign in</Link><Link to="/register" className="primary-button">Get started <ArrowUpRight size={15} /></Link></div></header>
    <main>
      <section className="landing-hero"><motion.div className="hero-copy" initial={reducedMotion ? false : { opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: .55 }}><p className="eyebrow"><span className="live-dot" /> YOUR DOCUMENTS. YOUR WAY.</p><h1>Less paperwork.<br />More <em>possibility.</em></h1><p className="hero-description">A considered workspace for your PDFs. Edit text, arrange pages, add your signature, and get back to the work that matters.</p><div className="hero-actions"><Link to="/register" className="primary-button">Start editing for free <ArrowRight size={17} /></Link><a href="#editor" className="text-link">Take a closer look <ArrowUpRight size={16} /></a></div><p className="hero-note">Free to edit. Export from ₦500. No subscription required.</p></motion.div><div className="hero-product" aria-label="Illustration of the Papertrail editor"><div className="demo-top"><span><FileText size={15} /> Your next big idea.pdf</span><span className="demo-saved"><Check size={12} /> Saved</span></div><div className="demo-body"><div className="demo-rail" aria-hidden="true"><MousePointer2 /><Type /><Image /><PenLine /><StickyNote /></div><div className="demo-paper"><span className="demo-label">PROJECT / 001</span><h2>A fresh<br />perspective.</h2><div className="demo-rule" /><p>Good ideas deserve a clear page.</p><div className="demo-edit">Make room for what comes next.<span className="demo-cursor">You</span></div><div className="demo-lines" /><div className="demo-signature">Made for the way you work.</div><span className="demo-page-number">PAPERTRAIL — 01</span></div></div><span className="demo-caption">Edit · Organize · Export</span></div></section>
      <section id="editor" className="landing-section feature-section"><div className="section-intro"><p className="eyebrow">FROM FIRST EDIT TO FINAL FILE</p><h2>A PDF is a starting point.<br />Not the end of the story.</h2><p>One browser workspace for the changes, details, and finishing touches that make a document yours.</p></div><div className="feature-grid">{[{ icon: Type, title: 'Change the words.', text: 'Edit supported existing PDF text or add new text exactly where you need it.' }, { icon: PenLine, title: 'Add your touch.', text: 'Place images, draw, add notes, create a signature, or apply a watermark.' }, { icon: FileText, title: 'Put it in order.', text: 'Manage pages, find text, undo changes, save your work, and return to your documents.' }].map(({ icon: Icon, title, text }, i) => <article key={title}><span className="feature-index">0{i + 1}</span><Icon size={24} /><h3>{title}</h3><p>{text}</p></article>)}</div><p className="capability-note">PDFs vary. Text editing and font fidelity depend on the source document.</p></section>
      <section id="tools" className="landing-section"><div className="section-intro horizontal"><div><p className="eyebrow">THE REST OF YOUR TOOLKIT</p><h2>Small tasks. Sorted.</h2></div><p>Keep the whole PDF workflow in one place, from combining files to converting pages.</p></div><motion.div initial={reducedMotion ? false : { opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, amount: .1 }} transition={{ duration: .45 }}><ToolCatalog /></motion.div></section>
      <section id="pricing" className="landing-section pricing-section"><div className="section-intro"><p className="eyebrow">PAY FOR WHAT YOU NEED</p><h2>Your edit is free.<br />Your export, your choice.</h2><p>One document or an everyday workflow. Choose what fits.</p></div><div className="pricing-grid">{[
        { name: 'Free', price: '₦0', suffix: 'to start', intro: 'Get your document just right.', features: ['Experience the core PDF editor', 'Edit text and add finishing touches', 'Pay when you need the final export'], cta: 'Start editing', featured: false },
        { name: 'One-Time Export', price: '₦500', suffix: 'per document', intro: 'For the PDF you need today.', features: ['Export your document', 'Re-export that document for 7 days', 'No subscription required'], cta: 'Get started', featured: true },
        { name: 'Papertrail Pro', price: '₦5,000', suffix: 'per month', intro: 'For documents that keep coming.', features: ['Unlimited exports and higher limits', 'Full version history', 'Premium PDF tools'], cta: 'Explore Pro', featured: false },
      ].map(plan => <article className={plan.featured ? 'price-card featured' : 'price-card'} key={plan.name}>{plan.featured && <span className="price-ribbon">NO COMMITMENT</span>}<h3>{plan.name}</h3><p>{plan.intro}</p><div className="price-value">{plan.price}<small>{plan.suffix}</small></div><ul>{plan.features.map(feature => <li key={feature}><Check size={16} />{feature}</li>)}</ul><Link className={plan.featured ? 'primary-button' : 'toolbar-button bordered'} to="/register">{plan.cta}<ArrowUpRight size={15} /></Link></article>)}</div><p className="pricing-footnote">Pro by card renews monthly. Pro by bank transfer gives one month of access without automatic renewal.</p></section>
      <section className="landing-cta"><p className="eyebrow">THE NEXT PAGE IS YOURS</p><h2>Make something<br /><em>ready to send.</em></h2><Link className="primary-button" to="/register">Open your workspace <ArrowRight size={17} /></Link></section>
    </main><footer className="landing-footer"><Brand /><span>Your document workspace.</span><Link to="/login">Sign in</Link><Link to="/support">Help & feedback</Link><a href="#pricing">Pricing</a></footer>
  </div>
}
